### ISSUE TITLE
注册问题

### ISSUE THREAD

**Issue by flysee** [demi520/wxapp-login-regist#1]
就是点击发送验证码按钮之后，绑定了个方法，但怎么去获取手机号，然后发送呢？探讨探讨哈

**Comment by demi520** [comment]
在找回密码页面里面有处理方式，注册页面当时忘记做这一步了，我稍后会重新提交一版
 <input id="username" name="username" maxlength='11' type="text"  placeholder="手机号" bindchange="getPhoneNum" />

getPhoneNum:function(e){
   var value  = e.detail.value;
   this.setData({
    phoneNum: value     
   });
  },

**Comment by yuanyang749** [comment]
@flysee 
在找回密码页面里面有处理方式，注册页面当时忘记做这一步了，我稍后会重新提交一版
getPhoneNum:function(e){
var value = e.detail.value;
this.setData({
phoneNum: value
});
},

**Comment by flysee** [comment]
@demi520 
嗯，顺便问个问题。
就是假设：循环列出一组电影列表，然后要给电影增加点赞功能。这个点赞操作怎么实现呢？
类似：
`<view bindtap='aa' data-id="a1">{{zan}}</view>`
`<view bindtap='aa' data-id="a2">{{zan}}</view>`
......
点击点赞后，应该都是到同个aa方法，然后去修改zan的值去修改图标，显示点赞了。
遇到的问题：修改zan的值，会修改所有的列表。
谢谢了

**Comment by yuanyang749** [comment]
@flysee 
{{zan}}定义一个变量肯定是不行的，肯定会同时改变，可以用以下方式解决：

`<view bindtap="aa" wx:for="{{array}}"  data-id='{{item.id}}'>
   {{item.zan}}
</view>`
data:{
     array: [
      {
        id:"a1",
        zan: '赞'
      }, 
      {
        id:"a2",
        zan: '赞'
      }
    ]
  },

aa:function(e){
    var currId = e.currentTarget.dataset.id;
    var array = this.data.array;
    for(var i = 0;i<array.length;i++){
      if(array[i]['id']==currId){
        array[i]['zan'] = "已赞";
        this.setData({
          array:array
        });
      }
    }
  }
不一定是最好的方式，如果有更好的方式也可以@我，谢谢

**Comment by flysee** [comment]
@demi520 
我有想过把赞和已赞放在一个数组里，但也需要
array: [
{
id:"a1",
zan: '赞'
},{
id:"a2",
zan: '赞'
}]},
这样的数组来存放id对应的点赞状态。
就是如果电影id多了，以及下拉加载更多的时候，这个数组是不是变得很大。
主要每次点赞操作，就得重新渲染所有电影的点赞状态。会不会性能不好？
感觉没类似js里document.getElementById('a').text='a';这样来设置。
当然有解决方法总比没好，谢谢了！
